name: Lint Code Files

on:
  push:
    branches:
      - main
      - dp-patch
  pull_request:
    branches:
      - main
      - dp-patch

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Markdown Linting
    - name: Install markdownlint
      run: npm install -g markdownlint-cli

    - name: Lint Markdown Files
      run: markdownlint "**/*.md"

    # Python Linting
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint Python Files
      run: flake8 .

    # Java Linting (no class-to-filename matching)
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Lint Java Files with Checkstyle
      run: |
        curl -O https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.5.0/checkstyle-10.5.0-all.jar
        java -jar checkstyle-10.5.0-all.jar -c /google_checks.xml **/*.java || true

    # Text File Check
    - name: Check Text Files for TODOs
      run: |
        if grep -rn 'TODO' **/*.txt; then
          echo "Found TODO in text files!"
          exit 1
        fi
